### ISSUE TITLE
用http时有没有遇到这个bug的

### ISSUE THREAD

**Issue by panda2012** [zhayujie/bot-on-anything#102]
[2023-03-08 15:26:25,894] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/bot-on-anything/channel/http/http_channel.py", line 50, in login
    response.set_cookie(key='Authorization', value=token)
  File "/usr/local/python3/lib/python3.8/site-packages/werkzeug/sansio/response.py", line 230, in set_cookie
    dump_cookie(
  File "/usr/local/python3/lib/python3.8/site-packages/werkzeug/http.py", line 1229, in dump_cookie
    value = _to_bytes(value, charset)
  File "/usr/local/python3/lib/python3.8/site-packages/werkzeug/_internal.py", line 107, in _to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes

**Comment by RegimenArsenic** [comment]
http需要pip install PyJWT，你可能是安成jwt了

**Comment by RegimenArsenic** [comment]
> > http需要pip install PyJWT，你可能是安成jwt了
> 
> PyJWT 2.6.0 已经装上了，还是报那个错误

PyJWT和jwt两个包的路径都是jwt，你可能需要把jwt卸载了才能正常使用Pyjwt

**Comment by panda2012** [comment]
已经卸载了

**Comment by panda2012** [comment]
> > > http需要pip install PyJWT，你可能是安成jwt了
> > 
> > 
> > PyJWT 2.6.0 已经装上了，还是报那个错误
> 
> PyJWT和jwt两个包的路径都是jwt，你可能需要把jwt卸载了才能正常使用Pyjwt

已经卸载了

**Comment by RegimenArsenic** [comment]
> > > > http需要pip install PyJWT，你可能是安成jwt了
> > > 
> > > 
> > > PyJWT 2.6.0 已经装上了，还是报那个错误
> > 
> > 
> > PyJWT和jwt两个包的路径都是jwt，你可能需要把jwt卸载了才能正常使用Pyjwt
> 
> 已经卸载了

File "/home/bot-on-anything/channel/http/http_channel.py", line 50, in login
response.set_cookie(key='Authorization', value=token)
方便在这里之前输出下token吗，看看是什么内容

**Comment by panda2012** [comment]
> > > > > http需要pip install PyJWT，你可能是安成jwt了
> > > > 
> > > > 
> > > > PyJWT 2.6.0 已经装上了，还是报那个错误
> > > 
> > > 
> > > PyJWT和jwt两个包的路径都是jwt，你可能需要把jwt卸载了才能正常使用Pyjwt
> > 
> > 
> > 已经卸载了
> 
> File "/home/bot-on-anything/channel/http/http_channel.py", line 50, in login response.set_cookie(key='Authorization', value=token) 方便在这里之前输出下token吗，看看是什么内容

把jwt和PyJWT卸载了，重新再安装一下就可以了，谢谢
