### ISSUE TITLE
接入微信个人账号，私聊有时候会无响应，似乎和特殊字符微信昵称有关

### ISSUE THREAD

**Issue by DBinK** [zhayujie/bot-on-anything#131]
具体表现为对方向机器人发送消息后，控制台有这个报错

```
Traceback (most recent call last):
  File "C:\Users\dbink\.pyenv\pyenv-win\versions\3.10.9\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "D:\IT_Program\bot-on-anything\channel\wechat\wechat_channel.py", line 34, in handler_single_msg
    WechatChannel().handle(msg)
  File "D:\IT_Program\bot-on-anything\channel\wechat\wechat_channel.py", line 65, in handle
    other_user_id = msg['User']['UserName']     # 对手方id
KeyError: 'UserName'
```

**Comment by zhayujie** [comment]
如果只是个别用户的话，那原因就是收到的微信消息里没有 发送人用户名这个字段

**Comment by DBinK** [comment]
一些出现过的无响应的微信昵称（一行一个）

ppo🐏🦅辰
____


> 如果只是个别用户的话，那原因就是收到的微信消息里没有 发送人用户名这个字段

一些出现过的无响应的微信昵称（一行一个）

ppo🐏🦅辰
____
