### ISSUE TITLE
bing接入微信提示IndexError: list index out of range

### ISSUE THREAD

**Issue by linmp4** [zhayujie/bot-on-anything#184]
H:\github\bot-on-anything>python.exe app.py
Load config success
[INFO][2023-03-22 08:47:34][log.py:34] - [INIT] Start up: bing on wechat
Please press confirm on your phone.
Log in time out, reloading QR code.
Please press confirm on your phone.
Log in time out, reloading QR code.
Please press confirm on your phone.
[ERROR][2023-03-22 08:48:08][log.py:45] - App startup failed!
[ERROR][2023-03-22 08:48:08][log.py:50] - list index out of range
Traceback (most recent call last):
  File "H:\github\bot-on-anything\app.py", line 32, in <module>
    start_process(channel_type)
  File "H:\github\bot-on-anything\app.py", line 19, in start_process
    channel.startup()
  File "H:\github\bot-on-anything\channel\wechat\wechat_channel.py", line 46, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\components\register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\components\login.py", line 60, in login
    status = self.check_login()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\components\login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\itchat\components\login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by linmp4** [comment]
暂时解决了，手机微信上取消登录，重新运行程序，会弹出登录二维码，重新扫描就可以了

**Comment by hecarli555** [comment]
> 暂时解决了，手机微信上取消登录，重新运行程序，会弹出登录二维码，重新扫描就可以了

我也是这个提示。。。。。详细应该怎么操作解决呢？

**Comment by hecarli555** [comment]
扫码第一次之后，要是掉线了再次执行运行命令，二维码都出不来了，，，，

**Comment by linmp4** [comment]
> 扫码第一次之后，要是掉线了再次执行运行命令，二维码都出不来了，，，，

需要在手机弹出登录确认的时候，按退出登录，然后再运行一次命令，就会出二维码了

**Comment by hecarli555** [comment]
学习了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linmp4 ***@***.***&gt;
发送时间: 2023年3月26日 22:02
收件人: zhayujie/bot-on-anything ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhayujie/bot-on-anything] 个人微信登录后提示IndexError: list index out of range (Issue #184)





  
扫码第一次之后，要是掉线了再次执行运行命令，二维码都出不来了，，，，
  
需要在手机弹出登录确认的时候，按退出登录，然后再运行一次命令，就会出二维码了

**Comment by mrilboom** [comment]
新用户貌似需要开通微信支付才能够登上
