### ISSUE TITLE
没有监控网络，求大佬看一下怎么回事

### ISSUE THREAD

**Issue by wanjia66** [zhayujie/bot-on-anything#193]
![image](https://user-images.githubusercontent.com/128202064/227232934-6e37e0da-1c8b-427f-8b6b-b167e2bbaed5.png)
C:\Users\Administrator\bot-on-anything>app.py
Load config success
[INFO][2023-03-23 22:11:12][log.py:34] - [INIT] Start up: wechat_mp on terminal

Please input your question
User:

**Comment by wanjia66** [comment]
输入app.py 变成这样了 

C:\Users\Administrator\bot-on-anything>app.py
Load config success
[INFO][2023-03-23 22:53:52][log.py:34] - [INIT] Start up: wechat_mp on terminal

Please input your question
User:
hello
Bot:
[ERROR][2023-03-23 22:53:57][log.py:45] - App startup failed!
[ERROR][2023-03-23 22:53:57][log.py:50] -
Traceback (most recent call last):
  File "C:\Users\Administrator\bot-on-anything\app.py", line 37, in <module>
    start_process(channel_type[0])
  File "C:\Users\Administrator\bot-on-anything\app.py", line 19, in start_process
    channel.startup()
  File "C:\Users\Administrator\bot-on-anything\channel\terminal\terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "C:\Users\Administrator\bot-on-anything\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "C:\Users\Administrator\bot-on-anything\bridge\bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "C:\Users\Administrator\bot-on-anything\model\model_factory.py", line 32, in create_bot
    raise RuntimeError
RuntimeError

**Comment by wanjia66** [comment]
config.json
![image](https://user-images.githubusercontent.com/128202064/227701160-5a5b22d2-4733-45bb-83d9-0b5d51a418b0.png)


> 看下你的 config.json
> 
> model type 配置的是什么

**Comment by wanjia66** [comment]
> 
"type" : "wechat_mp",就是这个

**Comment by zhayujie** [comment]
model type选择的是模型的类型哈，应该填 chatgpt，   下面 channel模块的type可以填写 wechat_mp
