### ISSUE TITLE
 EdgeGPT “ImageGen.py", line 49, in get_images raise Exception("Redirect failed")

### ISSUE THREAD

**Issue by linmp4** [zhayujie/bot-on-anything#198]
应该是问了一些无法生成图片的问题，然后就报错了

[ERROR][2023-03-25 14:26:40][log.py:50] - Redirect failed
Traceback (most recent call last):
  File "H:\github\bot-on-anything\model\bing\new_bing_model.py", line 99, in create_img
    img_list = image_generator.get_images(query)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ImageGen.py", line 49, in get_images
    raise Exception("Redirect failed")
Exception: Redirect failed

**Comment by RegimenArsenic** [comment]
#200 增加了错误提示,按微软的给的信息看,如果违反图片内容生成政策次数太多的话,账号可能会被暂停服务
