### ISSUE TITLE
【网页版】本地PyCharm正常启动，但登录以后报错

### ISSUE THREAD

**Issue by jihaonan** [zhayujie/bot-on-anything#203]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：3.7.4
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

> 简要说明、截图、复现步骤等，也可以是需求或想法

浏览器报错截图
![1679814590879](https://user-images.githubusercontent.com/14744832/227761527-81eeb1c3-ec7d-4bc6-aab0-0dd13cb83336.jpg)

### 终端日志 (如有报错)

```
E:\Python-WorkSpace\bot-on-anything\venv\Scripts\python.exe E:/Python-WorkSpace/bot-on-anything/app.py
Load config success
Load config success
[INFO][2023-03-26 15:08:06][log.py:34] - [INIT] Start up: chatgpt on http
 * Serving Flask app 'channel.http.http_channel'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.31.247:8080
Press CTRL+C to quit
127.0.0.1 - - [26/Mar/2023 15:08:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2023 15:08:13] "GET /favicon.ico HTTP/1.1" 404 -
[2023-03-26 15:08:22,985] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\Python-WorkSpace\bot-on-anything\channel\http\http_channel.py", line 53, in login
    response.set_cookie(key='Authorization', value=token)
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\werkzeug\sansio\response.py", line 241, in set_cookie
    samesite=samesite,
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\werkzeug\http.py", line 1229, in dump_cookie
    value = _to_bytes(value, charset)
  File "E:\Python-WorkSpace\bot-on-anything\venv\lib\site-packages\werkzeug\_internal.py", line 107, in _to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes
127.0.0.1 - - [26/Mar/2023 15:08:22] "POST /login HTTP/1.1" 500 -

```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：Windows10
 - Python版本  ( 执行 `python3 -V` )：3.7.4              
 - pip版本  ( 依赖问题此项必填，执行 `pip3 -V`)：19.0.3
 - 在PyCharm中启动

**Comment by RegimenArsenic** [comment]
需要安装PyJWT,看下是不是安装成jwt了

**Comment by jihaonan** [comment]
> 需要安装PyJWT,看下是不是安装成jwt了
已经安装的哈，没安装的话启动就报错，我这个是已经成功启动且能访问登录页面，但登录进去以后就报500错误
![image](https://user-images.githubusercontent.com/14744832/227769878-9f572e18-d78a-41ac-91db-2c741e197e60.png)

**Comment by RegimenArsenic** [comment]
需要的包是PyJWT,不是jwt

**Comment by jihaonan** [comment]
> 



> 

果然引了PyJWT就可以了，多谢多谢！
![image](https://user-images.githubusercontent.com/14744832/227775361-566df601-e025-41bb-8712-172409023e53.png)

**Comment by Jeffiano** [comment]
初次运行遇到同样的问题，执行pip3 install PyJWT之后正常了
