### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by linmp4** [zhayujie/bot-on-anything#209]
[ERROR][2023-03-26 21:15:26][wechat_channel.py:163] - unsupported operand type(s) for |: 'type' and 'NoneType'
Traceback (most recent call last):
  File "H:\github\bot-on-anything\channel\wechat\wechat_channel.py", line 159, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "H:\github\bot-on-anything\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "H:\github\bot-on-anything\bridge\bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "H:\github\bot-on-anything\model\model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "H:\github\bot-on-anything\model\bing\new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "H:\github\bot-on-anything\model\bing\jailbroken_sydney.py", line 13, in <module>
    class SydneyBot(Chatbot):
  File "H:\github\bot-on-anything\model\bing\jailbroken_sydney.py", line 17, in SydneyBot
    cookies: dict | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by RegimenArsenic** [comment]
EdgeGPT版本更新引起的bug,见 #211

**Comment by RegimenArsenic** [comment]
看叉了,你这个报错是因为python版本太低如果不想升级python版本的话,你要把所有用Union Types(使用"|"来确定变量属于多个类型)的代码
```
        cookies: dict | None = None,
```
改成这样
```
        cookies: dict  = None,
```

**Comment by linmp4** [comment]
更新了Python 3.10.10，没有报这个错误了。[https://www.python.org/downloads/release/python-31010/](url)

**Comment by 8955107** [comment]
> 



> 看叉了,你这个报错是因为python版本太低如果不想升级python版本的话,你要把所有用Union Types(使用"|"来确定变量属于多个类型)的代码
> 
> ```
>         cookies: dict | None = None,
> ```
> 
> 改成这样
> 
> ```
>         cookies: dict  = None,
> ```

按照如上方法修改后，会报错，请大神知道一下具体要怎么改呢？
![image](https://user-images.githubusercontent.com/62317011/228797127-88711349-b4fa-4908-aeef-97bdc8e9c76a.png)

**Comment by fengzai6** [comment]
楼上记得删完带 | 的全部
