### ISSUE TITLE
请再问我一次吧

### ISSUE THREAD

**Issue by bboychencan** [zhayujie/bot-on-anything#21]
[INFO][2023-02-21 15:44:50][open_ai_bot.py:20] - [OPEN_AI] query=吧
[ERROR][2023-02-21 15:44:55][open_ai_bot.py:64] - Internal server error {
"error": {
"message": "Internal server error",
"type": "auth_subrequest_error",
"param": null,
"code": "internal_error"
}
}
500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 07:44:55 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'bbbcfa735c6c715e8fdd7677b0773558', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
Traceback (most recent call last):
File "/home/lighthouse/chatgpt-on-wechat003/bot/openai/open_ai_bot.py", line 40, in reply_text
response = openai.Completion.create(
File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
return super().create(*args, **kwargs)
File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
resp, got_stream = self._interpret_response(result, stream)
File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
self._interpret_response_line(
File "/home/lighthouse/miniconda3/envs/chatgpt-wechat-bot/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
raise self.handle_error_response(
openai.error.APIError: Internal server error {
"error": {
"message": "Internal server error",
"type": "auth_subrequest_error",
"param": null,
"code": "internal_error"
}
}
500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 21 Feb 2023 07:44:55 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': 'bbbcfa735c6c715e8fdd7677b0773558', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
[INFO][2023-02-21 15:44:55][wechat_channel.py:103] - [WX] sendMsg=请再问我一次吧, receiver=@0d2b74afb9ab3fc0554dfb5c2e6a05b5

**Comment by zhayujie** [comment]
这个是openai服务挂了，已恢复

**Comment by ytking** [comment]
提示：请再问我一次吧。key是sk-后面的
openai.error.AuthenticationError: Incorrect API key provided: YOUR API KEY. You can find your API key at https://platform.openai.com/account/api-keys
