### ISSUE TITLE
web网页版提示网络故障，后台显示nonetype

### ISSUE THREAD

**Issue by gwailee** [zhayujie/bot-on-anything#210]
我的json设置是这样的（http_auth_secret_key没有改）：
"http_auth_secret_key": "6d25a684-9558-11e9-aa94-efccd7a0659b",
      "http_auth_password": "",
      "port": "8081"

用了80反向代理8081；
运行后后台报错：
[INFO][2023-03-26 13:40:17][log.py:32] - [CHATGPT] query=你好
[2023-03-26 13:40:17,640] ERROR in app: Exception on /chat [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/channel/http/http_channel.py", line 31, in chat
    reply_text = HttpChannel().handle(data=data)
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/channel/http/http_channel.py", line 74, in handle
    reply = super().build_reply_content(data["msg"], context)
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/bridge/bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/model/openai/chatgpt_model.py", line 25, in reply
    clear_memory_commands = common_conf_val('clear_memory_commands', ['#清除记忆'])
  File "/www/wwwroot/chatgpt.uqtool.com/web301-1/config.py", line 62, in common_conf_val
    return config.get('common').get(key, default)
AttributeError: 'NoneType' object has no attribute 'get'
127.0.0.1 - - [26/Mar/2023 13:40:17] "POST /chat HTTP/1.1" 500 -

**Comment by RegimenArsenic** [comment]
你可能需要在配置文件里加上
```
"common": {
    "clear_memory_commands": ["#清除记忆"]
  }
```

**Comment by zhayujie** [comment]
配置兼容有点问题，已修复

**Comment by chinesewebman** [comment]
刚刚clone部署的。同样的报错，网页版可以看到欢迎页面，问了第一句之后显示网络故障，对话未送达。日志里是这样：

> [2023-03-27 06:35:36,143] ERROR in app: Exception on /chat [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/root/bot-on-anything/channel/http/http_channel.py", line 31, in chat
>     reply_text = HttpChannel().handle(data=data)
>   File "/root/bot-on-anything/channel/http/http_channel.py", line 67, in handle
>     img_match_prefix = functions.check_prefix(
>   File "/root/bot-on-anything/common/functions.py", line 14, in check_prefix
>     for prefix in prefix_list:
> TypeError: 'NoneType' object is not iterable
>

**Comment by fangfang333** [comment]
我的也显示网络故障，
网页版：
GET http://10.10.10.21:10014/favicon.ico 404 (NOT FOUND)，POST http://10.10.10.21:10014/chat 500 (INTERNAL SERVER ERROR)，
后台显示：
root@debian:/opt/bot-on-anything# python3 /opt/bot-on-anything/app.py
Load config success
Load config success
[INFO][2023-03-27 17:52:39][log.py:34] - [INIT] Start up: chatgpt on http
 * Serving Flask app 'channel.http.http_channel'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10014
 * Running on http://10.10.10.21:10014
Press CTRL+C to quit
不用网页版改成订阅号，有时候能"还在处理中，请稍后再试"，有时候直接提示"该公众号提供的服务出现故障，请稍后再试"

**Comment by fangfang333** [comment]
没事了。我更新了1.0版本就好了，昨天晚上的版本就报错

**Comment by RegimenArsenic** [comment]
> 刚刚clone部署的。同样的报错，网页版可以看到欢迎页面，问了第一句之后显示网络故障，对话未送达。日志里是这样：
> 
> > [2023-03-27 06:35:36,143] ERROR in app: Exception on /chat [POST]
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
> > response = self.full_dispatch_request()
> > File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
> > rv = self.handle_user_exception(e)
> > File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
> > rv = self.dispatch_request()
> > File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
> > return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> > File "/root/bot-on-anything/channel/http/http_channel.py", line 31, in chat
> > reply_text = HttpChannel().handle(data=data)
> > File "/root/bot-on-anything/channel/http/http_channel.py", line 67, in handle
> > img_match_prefix = functions.check_prefix(
> > File "/root/bot-on-anything/common/functions.py", line 14, in check_prefix
> > for prefix in prefix_list:
> > TypeError: 'NoneType' object is not iterable

你的配置文件config.json里有配置image_create_prefix属性吗？

**Comment by chinesewebman** [comment]
没有配置image_create_prefix

**Comment by fangfang333** [comment]
> 没有配置image_create_prefix

我只启用wechat_mp的时候确实是没有配置image_create_prefix的，但是我不用http功能啊，在我只使用http的时候是有配置image_create_prefix的，也一样的报错，不过新版本已经能正常用了，现在养成习惯，不删任何行，只修改参数，谢谢啦
