### ISSUE TITLE
网页端一打开网址输入密码就会报错

### ISSUE THREAD

**Issue by gaoxiaokang** [zhayujie/bot-on-anything#217]

**Comment by gaoxiaokang** [comment]
显示 /internal servererror
the server encounter an 。。。。。ouerloaded

**Comment by Jeffiano** [comment]
> 显示 /internal servererror the server encounter an 。。。。。ouerloaded

控制台看下出错的日志

**Comment by RegimenArsenic** [comment]
可能没安装PyJWT包

**Comment by z673168469** [comment]
同问，楼主搞定了吗？

**Comment by z673168469** [comment]
我也是一登陆就提示错误信息：
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by gaoxiaokang** [comment]
> 可能没安装PyJWT包
显示已经安装了的

**Comment by gaoxiaokang** [comment]
还是原来的报错

**Comment by RegimenArsenic** [comment]
你要看后台报的什么错才能知道是什么问题

**Comment by z673168469** [comment]
我是登陆后提示这个错误，不知道楼主是不是：
[2023-03-29 18:51:09,828] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 50, in login
response.set_cookie(key='Authorization', value=token)
File "/usr/local/lib/python3.6/site-packages/werkzeug/sansio/response.py", line 245, in set_cookie
samesite=samesite,
File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1296, in dump_cookie
value = _to_bytes(value, charset)
File "/usr/local/lib/python3.6/site-packages/werkzeug/_internal.py", line 108, in _to_bytes
raise TypeError("Expected bytes")
TypeError: Expected bytes
43.207.68.134 - - [29/Mar/2023 18:51:09] "POST /login HTTP/1.1" 500 -

**Comment by gaoxiaokang** [comment]
是的



| |
g.
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月30日 08:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/bot-on-anything] 网页端一打开网址输入密码就会报错 (Issue #217) |

我是登陆后提示这个错误，不知道楼主是不是：
[2023-03-29 18:51:09,828] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 50, in login
response.set_cookie(key='Authorization', value=token)
File "/usr/local/lib/python3.6/site-packages/werkzeug/sansio/response.py", line 245, in set_cookie
samesite=samesite,
File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1296, in dump_cookie
value = _to_bytes(value, charset)
File "/usr/local/lib/python3.6/site-packages/werkzeug/_internal.py", line 108, in _to_bytes
raise TypeError("Expected bytes")
TypeError: Expected bytes
43.207.68.134 - - [29/Mar/2023 18:51:09] "POST /login HTTP/1.1" 500 -

**Comment by RegimenArsenic** [comment]
> 我是登陆后提示这个错误，不知道楼主是不是： [2023-03-29 18:51:09,828] ERROR in app: Exception on /login [POST] Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 50, in login response.set_cookie(key='Authorization', value=token) File "/usr/local/lib/python3.6/site-packages/werkzeug/sansio/response.py", line 245, in set_cookie samesite=samesite, File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1296, in dump_cookie value = _to_bytes(value, charset) File "/usr/local/lib/python3.6/site-packages/werkzeug/_internal.py", line 108, in _to_bytes raise TypeError("Expected bytes") TypeError: Expected bytes 43.207.68.134 - - [29/Mar/2023 18:51:09] "POST /login HTTP/1.1" 500 -


报这个错一般都是没装PyJWT包

**Comment by z673168469** [comment]
解决了谢谢，楼主 执行 pip3 install Pyjwt 即可！但又出现了  网络故障，对话未送达
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 28, in chat
    reply_text = HttpChannel().handle(data=data)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 65, in handle
    return super().build_reply_content(data["msg"], context)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/bridge/bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/model/openai/chatgpt_model.py", line 36, in reply
    reply_content = self.reply_text(new_query, from_user_id, 0)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/model/openai/chatgpt_model.py", line 74, in reply_text
    except openai.error.Timeout as e:
AttributeError: module 'openai.error' has no attribute 'Timeout'
43.207.68.134 - - [30/Mar/2023 10:43:25] "POST /chat HTTP/1.1" 500 -

**Comment by zyz3380** [comment]
我的也是这样，有解决方案吗大佬们
![11](https://user-images.githubusercontent.com/84485307/229452737-b32827db-8059-4cc4-9ff7-07762704a710.png)
