### ISSUE TITLE
web版登录后提示错误

### ISSUE THREAD

**Issue by z673168469** [zhayujie/bot-on-anything#226]
登陆后提示这个错误：
[2023-03-29 18:51:09,828] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tools/chat3.5/bot-on-anything-1.0.0/channel/http/http_channel.py", line 50, in login
    response.set_cookie(key='Authorization', value=token)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/sansio/response.py", line 245, in set_cookie
    samesite=samesite,
  File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1296, in dump_cookie
    value = _to_bytes(value, charset)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/_internal.py", line 108, in _to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes
43.207.68.134 - - [29/Mar/2023 18:51:09] "POST /login HTTP/1.1" 500 -

**Comment by RegimenArsenic** [comment]
报这个错一般都是没装PyJWT包，见#203

**Comment by z673168469** [comment]
解决了 pip3 install PyJWT
