### ISSUE TITLE
我在win10上用了加速器，在Linux虚拟机上运行，当微信发送消息时出现如下错误

### ISSUE THREAD

**Issue by ascout7** [zhayujie/bot-on-anything#245]
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
six. raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
response.begin()
File "/usr/lib/python3.10/http/client.py", line 318, in begin
version, status, reason = self._read_status()
File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions. ProtocolError: ('Connection aborted. ', RemoteDisconnected('Remote end closed connection without response'))

**Comment by hpsprger** [comment]
在微信公众号上使用，回复一直说:


&nbsp; &nbsp; &nbsp; 提问太快啦，请休息一下再问我吧


这个是什么情况







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月1日(周六) 晚上11:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhayujie/bot-on-anything] 我在win10上用了加速器，在Linux虚拟机上运行，当微信发送消息时出现如下错误 (Issue #245)




 
raise RemoteDisconnected("Remote end closed connection without"
 http.client.RemoteDisconnected: Remote end closed connection without response
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
 resp = conn.urlopen(
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
 retries = retries.increment(
 File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
 raise six.reraise(type(error), error, _stacktrace)
 File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
 raise value.with_traceback(tb)
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
 httplib_response = self._make_request(
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
 six. raise_from(e, None)
 File "", line 3, in raise_from
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
 httplib_response = conn.getresponse()
 File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
 response.begin()
 File "/usr/lib/python3.10/http/client.py", line 318, in begin
 version, status, reason = self._read_status()
 File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
 raise RemoteDisconnected("Remote end closed connection without"
 urllib3.exceptions. ProtocolError: ('Connection aborted. ', RemoteDisconnected('Remote end closed connection without response'))
