### ISSUE TITLE
请问，执行文档最后命令，服务没起来 有报错

### ISSUE THREAD

**Issue by ryan730** [zhayujie/bot-on-anything#247]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/14855190/229330285-bbcf2f65-7acc-4c1f-be3e-ab37378babb8.png">

$ python3 app.py  /   nohup python3 app.py & tail -f nohup.out
[3] 7025
Traceback (most recent call last):
  File "/bot-on-anything/app.py", line 37, in <module>
    start_process(channel_type[0])
  File "/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/bot-on-anything/channel/terminal/terminal_channel.py", line 14, in startup
    prompt = self.get_input("User:\n")
  File "/bot-on-anything/channel/terminal/terminal_channel.py", line 32, in get_input
    line = input()
OSError: [Errno 9] Bad file descriptor
Load config success
Load config success

**Comment by axzaxza** [comment]
怎么解决，一模一样
