### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by ZealerG** [zhayujie/bot-on-anything#25]
Traceback (most recent call last):
  File "app.py", line 22, in <module>
    channel.startup()
  File "/usr/src/bot-on-anything/channel/terminal/terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "/usr/src/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/usr/src/bot-on-anything/bridge/bridge.py", line 9, in fetch_reply_content
    return model_factory.create_bot(config.conf().get("model").get("type")).reply(query, context)
  File "/usr/src/bot-on-anything/model/model_factory.py", line 19, in create_bot
    raise RuntimeError
RuntimeError

你好 报了这个错 没找着是啥原因

**Comment by ZealerG** [comment]
然后用订阅号的话 订阅号会一直回复“还在处理中，请稍后再试”

**Comment by Lancenas** [comment]
> 然后用订阅号的话 订阅号会一直回复“还在处理中，请稍后再试”

配置channel-type错了吧.

**Comment by ZealerG** [comment]
> 

channel-type用terminal会报上面那个错 用wechat_mp一直得不到chatgpt的回复 发“继续”订阅号就回复“还在处理中，请稍后再试”

**Comment by ZealerG** [comment]
> 配置channel-type错了吧.
channel-type填terminal的话就会报上面那个RuntimeError  填wechat_mp的话就是得不到回复  发“继续”订阅号只会回复“还在处理中，请稍后再试”

**Comment by ZealerG** [comment]
> 配置channel-type错了吧.
channel-type填terminal的话就会报上面那个RuntimeError 填wechat_mp的话就是得不到回复 发“继续”订阅号只会回复“还在处理中，请稍后再试”

**Comment by zhayujie** [comment]
这个是 model部分的type配置有问题，有配成"openai"  吗， 配置文件可否贴一下

**Comment by ZealerG** [comment]
> 这个是 model部分的type配置有问题，有配成"openai" 吗， 配置文件可否贴一下

sry 找到问题所在了 看漏了 pip版本不够openai没装好 升级完pip再装一下openai就ok了 🐶
