### ISSUE TITLE
http 模块有问题

### ISSUE THREAD

**Issue by Albert-liulei** [zhayujie/bot-on-anything#251]
输入密码后页面显示：
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

程序报错：
1.119.161.30 - - [02/Apr/2023 17:49:19] "GET / HTTP/1.1" 200 -
1.119.161.30 - - [02/Apr/2023 17:49:19] "GET /favicon.ico HTTP/1.1" 404 -
[2023-04-02 17:49:42,693] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/bot-on-anything/channel/http/http_channel.py", line 53, in login
    response.set_cookie(key='Authorization', value=token)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/sansio/response.py", line 230, in set_cookie
    dump_cookie(
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/http.py", line 1229, in dump_cookie
    value = _to_bytes(value, charset)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/_internal.py", line 107, in _to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes

**Comment by RegimenArsenic** [comment]
见#203

**Comment by zhouzhiyi88** [comment]
@RegimenArsenic  请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！

**Comment by RegimenArsenic** [comment]
> @RegimenArsenic 请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！

#233已经修改,等待pr合并

**Comment by zyz3380** [comment]
网络故障，对话未送达是啥情况

**Comment by zhouzhiyi88** [comment]
@

> > @RegimenArsenic 请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！
> 
> #233 已经修改,等待pr合并,至于界面问题,现在能满足最基础的聊天需求,如果想要更华丽的界面效果,就需要引入vue或者react,这样还需要npm来打包,感觉仅仅只是为了一个聊天页面得不偿失,如果以后确实需要增加更多功能,在考虑修改前端页面吧

目前运行了最新的流式生成，遇到个问题。
File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type async_generator is not JSON serializable

**Comment by RegimenArsenic** [comment]
> @
> 
> > > @RegimenArsenic 请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！
> > 
> > 
> > #233 已经修改,等待pr合并,至于界面问题,现在能满足最基础的聊天需求,如果想要更华丽的界面效果,就需要引入vue或者react,这样还需要npm来打包,感觉仅仅只是为了一个聊天页面得不偿失,如果以后确实需要增加更多功能,在考虑修改前端页面吧
> 
> 目前运行了最新的流式生成，遇到个问题。 File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default raise TypeError(f"Object of type {type(o).**name**} is not JSON serializable") TypeError: Object of type async_generator is not JSON serializable

你这个报错信息太少，看不出来是哪报错，需要更多的上下文

**Comment by zhouzhiyi88** [comment]
> > @
> > > > @RegimenArsenic 请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！
> > > 
> > > 
> > > #233 已经修改,等待pr合并,至于界面问题,现在能满足最基础的聊天需求,如果想要更华丽的界面效果,就需要引入vue或者react,这样还需要npm来打包,感觉仅仅只是为了一个聊天页面得不偿失,如果以后确实需要增加更多功能,在考虑修改前端页面吧
> > 
> > 
> > 目前运行了最新的流式生成，遇到个问题。 File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default raise TypeError(f"Object of type {type(o).**name**} is not JSON serializable") TypeError: Object of type async_generator is not JSON serializable
> 
> 你这个报错信息太少，看不出来是哪报错，需要更多的上下文

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2156, in make_response
    rv = self.json.response(rv)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/python3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type async_generator is not JSON serializable

您好，完整错误是这个。环境：python3.7.1。多谢！

**Comment by RegimenArsenic** [comment]
> > > @
> > > > > @RegimenArsenic 请教个问题，关于Web端运行，遇到个问题：当返回的字符过多的时候，有时需要2分钟，会返回网络超时，但终端里显示有结果，尝试看了看1.js 这个文件，不知怎么修改。另一个是关于WEB界面，有是否考虑优化丰富点。谢谢！
> > > > 
> > > > 
> > > > #233 已经修改,等待pr合并,至于界面问题,现在能满足最基础的聊天需求,如果想要更华丽的界面效果,就需要引入vue或者react,这样还需要npm来打包,感觉仅仅只是为了一个聊天页面得不偿失,如果以后确实需要增加更多功能,在考虑修改前端页面吧
> > > 
> > > 
> > > 目前运行了最新的流式生成，遇到个问题。 File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default raise TypeError(f"Object of type {type(o).**name**} is not JSON serializable") TypeError: Object of type async_generator is not JSON serializable
> > 
> > 
> > 你这个报错信息太少，看不出来是哪报错，需要更多的上下文
> 
> Traceback (most recent call last): File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app response = self.full_dispatch_request() File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1826, in full_dispatch_request return self.finalize_request(rv) File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1845, in finalize_request response = self.make_response(rv) File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2156, in make_response rv = self.json.response(rv) File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 309, in response f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 230, in dumps return json.dumps(obj, **kwargs) File "/usr/local/python3/lib/python3.7/json/**init**.py", line 238, in dumps **kw).encode(obj) File "/usr/local/python3/lib/python3.7/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/local/python3/lib/python3.7/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/python3/lib/python3.7/site-packages/flask/json/provider.py", line 122, in _default raise TypeError(f"Object of type {type(o).**name**} is not JSON serializable") TypeError: Object of type async_generator is not JSON serializable
> 
> 您好，完整错误是这个。环境：python3.7.1。多谢！

你安装了flask_socketio了吗？

**Comment by zhouzhiyi88** [comment]
> flask_socketio

安装的Flask-SocketIO     5.3.3，clone的你主页的代码，由于在http_channel文件中默认使用的reply_text = HttpChannel().handle(data=data)，修改使用了成handle_stream方法。其他未改动，直接运行。就报上面问题。

**Comment by RegimenArsenic** [comment]
> > flask_socketio
> 
> 安装的Flask-SocketIO 5.3.3，clone的你主页的代码，由于在http_channel文件中默认使用的reply_text = HttpChannel().handle(data=data)，修改使用了成handle_stream方法。其他未改动，直接运行。就报上面问题。

不需要做任何修改，直接运行，是否选择流式对话是在网页上选择的
