### ISSUE TITLE
dingtalk_post_token是哪个token？

### ISSUE THREAD

**Issue by oldcai** [zhayujie/bot-on-anything#274]
在文档和后台都没有发现这个token

**Comment by gwailee** [comment]
同问，好像这个是旧版有，我看了钉钉的历史的文档有这两个。新版已经变成了只有三个参数：AgentId、AppKey和APPScrete；这一版本感觉不能接上钉钉。

**Comment by gwailee** [comment]
这个是升级文档，新的文档说了旧版本的不给申请了，新版本参数发生了变化，只能等作者升级了。钉钉升级机器人文档：https://open-dev.dingtalk.com/fe/old/#/noticeMsg/detail/254235/index

**Comment by winse** [comment]
dingtalk_post_token可以不用填的。从代码看，是dingtalk服务器发送消息过来的Token头。

这个v1的旧页面可以 https://open-dev.dingtalk.com/v1/fe/old#/corprobot 直接创建机器人。机器人应用凭证的AppSecret对应**dingtalk_secret**；发布机器人，把机器人加入到群后，机器人设置页面的webhook地址上的access_token对应的是**dingtalk_token**。

对回复图片也稍微改了一下，可以参考：
```
# encoding:utf-8
import json
import hmac
import hashlib
import base64
import time
import requests
from urllib.parse import quote_plus
from common import log
from flask import Flask, request, render_template, make_response
from common import const
from common import functions
from config import channel_conf
from config import channel_conf_val
from channel.channel import Channel

class DingTalkChannel(Channel):
    def __init__(self):
        self.dingtalk_token = channel_conf(const.DINGTALK).get('dingtalk_token')
        self.dingtalk_post_token = channel_conf(const.DINGTALK).get('dingtalk_post_token')
        self.dingtalk_secret = channel_conf(const.DINGTALK).get('dingtalk_secret')
        log.info("[DingTalk] dingtalk_secret={}, dingtalk_token={} dingtalk_post_token={}".format(self.dingtalk_secret, self.dingtalk_token, self.dingtalk_post_token))

    def startup(self):
        http_app.run(host='0.0.0.0', port=channel_conf(const.DINGTALK).get('port'))
        
    def notify_dingtalk(self, data):
        timestamp = round(time.time() * 1000)
        secret_enc = bytes(self.dingtalk_secret, encoding='utf-8')
        string_to_sign = '{}\n{}'.format(timestamp, self.dingtalk_secret)
        string_to_sign_enc = bytes(string_to_sign, encoding='utf-8')
        hmac_code = hmac.new(secret_enc, string_to_sign_enc,
                             digestmod=hashlib.sha256).digest()
        sign = quote_plus(base64.b64encode(hmac_code))

        notify_url = f"https://oapi.dingtalk.com/robot/send?access_token={self.dingtalk_token}&timestamp={timestamp}&sign={sign}"
        try:
            r = requests.post(notify_url, json=data)
            reply = r.json()
            # log.info("[DingTalk] reply={}".format(str(reply)))
        except Exception as e:
            log.error(e)

    def handle(self, resp):
        reply = "您好，有什么我可以帮助您解答的问题吗？"
        prompt = resp['text']['content']
        prompt = prompt.strip()
        if str(prompt) != 0:
            conversation_id = resp['conversationId']
            sender_id = resp['senderId']
            context = dict()
            img_match_prefix = functions.check_prefix(
                prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
            if img_match_prefix:
                prompt = prompt.split(img_match_prefix, 1)[1].strip()
                context['type'] = 'IMAGE_CREATE'
            id = sender_id
            nick = resp['senderNick']
            staffid = resp['senderStaffId']
            context['from_user_id'] = str(id)
            reply = super().build_reply_content(prompt, context)
        if img_match_prefix and isinstance(reply, list):
            images = ""
            for url in reply:
                images += f"!['IMAGE_CREATE']({url})\n"
            reply = images
            resp = {
                "msgtype": "markdown",
                "markdown": {
                    "title": "IMAGE @" + nick + " ", 
                    "text": images + " \n " + "@" + nick
                },
                "at": {
                    "atUserIds": [
                        staffid
                    ],
                    "isAtAll": False
                }
            }
        else:
            resp = {
                "msgtype": "text",
                "text": {
                    "content": reply
                },
                "at": {
                    "atUserIds": [
                       staffid 
                    ],
                    "isAtAll": False
                }
            }
        return resp 


dd = DingTalkChannel()
http_app = Flask(__name__,)


@http_app.route("/", methods=['POST'])
def chat():
    log.info("[DingTalk] chat_headers={}".format(str(request.headers)))
    log.info("[DingTalk] chat={}".format(str(request.data)))
    token = request.headers.get('token')
    if dd.dingtalk_post_token and token != dd.dingtalk_post_token:
        return {'ret': 203}
    data = json.loads(request.data)
    if data:
        content = data['text']['content']
        if not content:
            return
        reply = dd.handle(resp=data);
        dd.notify_dingtalk(reply)
        return {'ret': 200}
    return {'ret': 201}

```

**Comment by oldcai** [comment]
请问钉钉有办法不用@机器人就自动回复吗？

**Comment by gwailee** [comment]
> dingtalk_post_token可以不用填的。从代码看，是dingtalk服务器发送消息过来的Token头。
> 
> 这个v1的旧页面可以 https://open-dev.dingtalk.com/v1/fe/old#/corprobot 直接创建机器人。机器人应用凭证的AppSecret对应**dingtalk_secret**；发布机器人，把机器人加入到群后，机器人设置页面的webhook地址上的access_token对应的是**dingtalk_token**。
> 
> 对回复图片也稍微改了一下，可以参考：
> 
> ```
> # encoding:utf-8
> import json
> import hmac
> import hashlib
> import base64
> import time
> import requests
> from urllib.parse import quote_plus
> from common import log
> from flask import Flask, request, render_template, make_response
> from common import const
> from common import functions
> from config import channel_conf
> from config import channel_conf_val
> from channel.channel import Channel
> 
> class DingTalkChannel(Channel):
>     def __init__(self):
>         self.dingtalk_token = channel_conf(const.DINGTALK).get('dingtalk_token')
>         self.dingtalk_post_token = channel_conf(const.DINGTALK).get('dingtalk_post_token')
>         self.dingtalk_secret = channel_conf(const.DINGTALK).get('dingtalk_secret')
>         log.info("[DingTalk] dingtalk_secret={}, dingtalk_token={} dingtalk_post_token={}".format(self.dingtalk_secret, self.dingtalk_token, self.dingtalk_post_token))
> 
>     def startup(self):
>         http_app.run(host='0.0.0.0', port=channel_conf(const.DINGTALK).get('port'))
>         
>     def notify_dingtalk(self, data):
>         timestamp = round(time.time() * 1000)
>         secret_enc = bytes(self.dingtalk_secret, encoding='utf-8')
>         string_to_sign = '{}\n{}'.format(timestamp, self.dingtalk_secret)
>         string_to_sign_enc = bytes(string_to_sign, encoding='utf-8')
>         hmac_code = hmac.new(secret_enc, string_to_sign_enc,
>                              digestmod=hashlib.sha256).digest()
>         sign = quote_plus(base64.b64encode(hmac_code))
> 
>         notify_url = f"https://oapi.dingtalk.com/robot/send?access_token={self.dingtalk_token}&timestamp={timestamp}&sign={sign}"
>         try:
>             r = requests.post(notify_url, json=data)
>             reply = r.json()
>             # log.info("[DingTalk] reply={}".format(str(reply)))
>         except Exception as e:
>             log.error(e)
> 
>     def handle(self, resp):
>         reply = "您好，有什么我可以帮助您解答的问题吗？"
>         prompt = resp['text']['content']
>         prompt = prompt.strip()
>         if str(prompt) != 0:
>             conversation_id = resp['conversationId']
>             sender_id = resp['senderId']
>             context = dict()
>             img_match_prefix = functions.check_prefix(
>                 prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
>             if img_match_prefix:
>                 prompt = prompt.split(img_match_prefix, 1)[1].strip()
>                 context['type'] = 'IMAGE_CREATE'
>             id = sender_id
>             nick = resp['senderNick']
>             staffid = resp['senderStaffId']
>             context['from_user_id'] = str(id)
>             reply = super().build_reply_content(prompt, context)
>         if img_match_prefix and isinstance(reply, list):
>             images = ""
>             for url in reply:
>                 images += f"!['IMAGE_CREATE']({url})\n"
>             reply = images
>             resp = {
>                 "msgtype": "markdown",
>                 "markdown": {
>                     "title": "IMAGE @" + nick + " ", 
>                     "text": images + " \n " + "@" + nick
>                 },
>                 "at": {
>                     "atUserIds": [
>                         staffid
>                     ],
>                     "isAtAll": False
>                 }
>             }
>         else:
>             resp = {
>                 "msgtype": "text",
>                 "text": {
>                     "content": reply
>                 },
>                 "at": {
>                     "atUserIds": [
>                        staffid 
>                     ],
>                     "isAtAll": False
>                 }
>             }
>         return resp 
> 
> 
> dd = DingTalkChannel()
> http_app = Flask(__name__,)
> 
> 
> @http_app.route("/", methods=['POST'])
> def chat():
>     log.info("[DingTalk] chat_headers={}".format(str(request.headers)))
>     log.info("[DingTalk] chat={}".format(str(request.data)))
>     token = request.headers.get('token')
>     if dd.dingtalk_post_token and token != dd.dingtalk_post_token:
>         return {'ret': 203}
>     data = json.loads(request.data)
>     if data:
>         content = data['text']['content']
>         if not content:
>             return
>         reply = dd.handle(resp=data);
>         dd.notify_dingtalk(reply)
>         return {'ret': 200}
>     return {'ret': 201}
> ```

按照你的方式设置了，分别获得群里的机器人的webhoot的access_token和应用的APP_screte，分别填写到里面：
样式是这样的（真实值去了）：
 "dingtalk_token": "6d3019c62c8sgsdge9378a48e5e7308c94a3737b8510a1a0f850d222232a", 
      "dingtalk_post_token": "",
      "dingtalk_secret": "QWuhV97bFzhvQcysdggsd6zGN4gjm-vamljp2Ua15jvFmsjlUlKsD--7m0HQQY"
我也做了反向代理，也就是80》8081端口，后台能看到正常回复，但是没有返回到群里面来，这是什么问题？

**Comment by gwailee** [comment]
对了，也做了ip白名单

**Comment by winse** [comment]
增加多群配置：

```
    },

    "dingtalk": {
      "image_create_prefix": ["画", "draw", "Draw"],
      "port": "3000",
      "dingtalk_secret": "AppSecret",
      "dingtalk_token": "access_token",
      "dingtalk_post_token": "",
      "dingtalk_robots": ["Chat111", "Chat123"],
      "Chat111": { 
          "dingtalk_secret": "AppSecret_111",
          "dingtalk_token": "access_token_111",
          "dingtalk_post_token": ""
      }, 
      "Chat123": { 
          "dingtalk_secret": "AppSecret123",
          "dingtalk_token": "access_token_123",
          "dingtalk_post_token": ""
      }
    },

    "gmail": {
```

代码如下：

```
# encoding:utf-8
import json
import hmac
import hashlib
import base64
import time
import requests
from urllib.parse import quote_plus
from common import log
from flask import Flask, request, render_template, make_response
from common import const
from common import functions
from config import channel_conf
from config import channel_conf_val
from channel.channel import Channel


class DingTalkGroup():
    def __init__(self, group, config):
        self.dingtalk_token = config.get('dingtalk_token')
        self.dingtalk_post_token = config.get('dingtalk_post_token')
        self.dingtalk_secret = config.get('dingtalk_secret')
        log.info("[DingTalk] {} AppSecret={}, access_token={} Token={}".format(group, self.dingtalk_secret, self.dingtalk_token, self.dingtalk_post_token))

    def notify_dingtalk(self, data):
        timestamp = round(time.time() * 1000)
        secret_enc = bytes(self.dingtalk_secret, encoding='utf-8')
        string_to_sign = '{}\n{}'.format(timestamp, self.dingtalk_secret)
        string_to_sign_enc = bytes(string_to_sign, encoding='utf-8')
        hmac_code = hmac.new(secret_enc, string_to_sign_enc,
                             digestmod=hashlib.sha256).digest()
        sign = quote_plus(base64.b64encode(hmac_code))

        notify_url = f"https://oapi.dingtalk.com/robot/send?access_token={self.dingtalk_token}&timestamp={timestamp}&sign={sign}"
        try:
            r = requests.post(notify_url, json=data)
            reply = r.json()
            # log.info("[DingTalk] reply={}".format(str(reply)))
        except Exception as e:
            log.error(e)

    def chat(self, channel, message):
        reply_text = channel.handle(message)
        self.notify_dingtalk(reply_text)


class DingTalkChannel(Channel):
    def __init__(self):
        log.info("[DingTalk] started.")

    def startup(self):
        http_app.run(host='0.0.0.0', port=channel_conf(const.DINGTALK).get('port'))

    def handle(self, data):
        reply = "您好，有什么我可以帮助您解答的问题吗？"
        prompt = data['text']['content']
        prompt = prompt.strip()
        if str(prompt) != 0:
            conversation_id = data['conversationId']
            sender_id = data['senderId']
            context = dict()
            img_match_prefix = functions.check_prefix(
                prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
            if img_match_prefix:
                prompt = prompt.split(img_match_prefix, 1)[1].strip()
                context['type'] = 'IMAGE_CREATE'
            id = sender_id
            nick = data['senderNick']
            staffid = data['senderStaffId']
            context['from_user_id'] = str(id)
            reply = super().build_reply_content(prompt, context)
        if img_match_prefix and isinstance(reply, list):
            images = ""
            for url in reply:
                images += f"!['IMAGE_CREATE']({url})\n"
            reply = images
            resp = {
                "msgtype": "markdown",
                "markdown": {
                    "title": "IMAGE @" + nick + " ", 
                    "text": images + " \n " + "@" + nick
                },
                "at": {
                    "atUserIds": [
                        staffid
                    ],
                    "isAtAll": False
                }
            }
        else:
            resp = {
                "msgtype": "text",
                "text": {
                    "content": reply
                },
                "at": {
                    "atUserIds": [
                       staffid 
                    ],
                    "isAtAll": False
                }
            }
        return resp 

   
dd = DingTalkChannel()
groups = dict()
robots = channel_conf(const.DINGTALK).get('dingtalk_robots')
if len(robots) > 0:
    for robot in robots:
        robot_config = channel_conf(const.DINGTALK).get(robot)
        groups[robot] = DingTalkGroup(robot, robot_config)
else:
    groups['DEFAULT'] = DingTalkGroup("DEFAULT", channel_conf(const.DINGTALK))
http_app = Flask(__name__,)


@http_app.route("/", methods=['POST'])
def chat():
    log.info("[DingTalk] chat_headers={}".format(str(request.headers)))
    log.info("[DingTalk] chat={}".format(str(request.data)))
    token = request.headers.get('token')
    data = json.loads(request.data)
    if data:
        content = data['text']['content']
        if not content:
            return
        group_name = data['conversationTitle']
        group = groups.get(group_name, groups.get('DEFAULT'))
        if group.dingtalk_post_token and token != group.dingtalk_post_token:
            return {'ret': 203}
        group.chat(dd, data)
        return {'ret': 200}
    return {'ret': 201}


```

**Comment by winse** [comment]
单聊

```
# encoding:utf-8
import json
import hmac
import hashlib
import base64
import time
import requests
from urllib.parse import quote_plus
from common import log
from flask import Flask, request, render_template, make_response
from common import const
from common import functions
from config import channel_conf
from config import channel_conf_val
from channel.channel import Channel


class DingTalkHandler():
    def __init__(self, config):
        self.dingtalk_key = config.get('dingtalk_key')
        self.dingtalk_secret = config.get('dingtalk_secret')
        self.dingtalk_token = config.get('dingtalk_token')
        self.dingtalk_post_token = config.get('dingtalk_post_token')
        self.access_token = None
        log.info("[DingTalk] AppKey={}, AppSecret={} Token={} post Token={}".format(self.dingtalk_key, self.dingtalk_secret, self.dingtalk_token, self.dingtalk_post_token))

    def notify_dingtalk_webhook(self, data):
        timestamp = round(time.time() * 1000)
        secret_enc = bytes(self.dingtalk_secret, encoding='utf-8')
        string_to_sign = '{}\n{}'.format(timestamp, self.dingtalk_secret)
        string_to_sign_enc = bytes(string_to_sign, encoding='utf-8')
        hmac_code = hmac.new(secret_enc, string_to_sign_enc,
                             digestmod=hashlib.sha256).digest()
        sign = quote_plus(base64.b64encode(hmac_code))

        notify_url = f"https://oapi.dingtalk.com/robot/send?access_token={self.dingtalk_token}&timestamp={timestamp}&sign={sign}"
        try:
            log.info("[DingTalk] url={}".format(str(notify_url)))
            r = requests.post(notify_url, json=data)
            reply = r.json()
            log.info("[DingTalk] reply={}".format(str(reply)))
        except Exception as e:
            log.error(e)

    def get_token_internal(self):
        access_token_url = 'https://api.dingtalk.com/v1.0/oauth2/accessToken'
        try:
            r = requests.post(access_token_url, json={"appKey": self.dingtalk_key, "appSecret": self.dingtalk_secret})
        except:
            raise Exception("DingTalk token获取失败!!!")

        data = json.loads(r.content)
        access_token = data['accessToken']
        expire_in = data['expireIn']
        
        self.access_token = access_token
        self.expire_at = int(expire_in) + time.time()

        return self.access_token
    
    def get_token(self):
        if self.access_token is None or self.expire_at <= time.time():
            self.get_token_internal()
        
        return self.access_token
    
    def get_post_url(self, data):
        type = data['conversationType']
        if type == "1":
            return f"https://api.dingtalk.com/v1.0/robot/oToMessages/batchSend"
        else:
            return f"https://api.dingtalk.com/v1.0/robot/groupMessages/send"
    
    def build_response(self, reply, data):
        type = data['conversationType']
        if type == "1":
            return self.build_oto_response(reply, data)
        else:
            return self.build_group_response(reply, data)

    def build_oto_response(self, reply, data):
        conversation_id = data['conversationId']
        prompt = data['text']['content']
        prompt = prompt.strip()
        img_match_prefix = functions.check_prefix(
            prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
        nick = data['senderNick']
        staffid = data['senderStaffId']
        robotCode = data['robotCode']
        if img_match_prefix and isinstance(reply, list):
            images = ""
            for url in reply:
                images += f"!['IMAGE_CREATE']({url})\n"
            reply = images
            resp = {
                "msgKey": "sampleMarkdown",
                "msgParam": json.dumps({
                    "title": "IMAGE @" + nick + " ", 
                    "text": images + " \n " + "@" + nick
                }),
                "robotCode": robotCode,
                "userIds": [staffid]
            }
        else:
            resp = {
                "msgKey": "sampleText",
                "msgParam": json.dumps({
                    "content": reply
                }),
                "robotCode": robotCode,
                "userIds": [staffid]
            }
        return resp
    
    def build_group_response(self, reply, data):
        conversation_id = data['conversationId']
        prompt = data['text']['content']
        prompt = prompt.strip()
        img_match_prefix = functions.check_prefix(
            prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
        nick = data['senderNick']
        staffid = data['senderStaffId']
        robot_code = data['robotCode']
        if img_match_prefix and isinstance(reply, list):
            images = ""
            for url in reply:
                images += f"!['IMAGE_CREATE']({url})\n"
            reply = images
            resp = {
                "msgKey": "sampleMarkdown",
                "msgParam": json.dumps({
                    "title": "IMAGE @" + nick + " ", 
                    "text": images + " \n " + "@" + nick
                }),
                "robotCode": robot_code,
                "openConversationId": conversation_id,
                "at": {
                    "atUserIds": [
                        staffid
                    ],
                    "isAtAll": False
                }
            }
        else:
            resp = {
                "msgKey": "sampleText",
                "msgParam": json.dumps({
                    "content": reply + " \n " + "@" + nick
                }),
                "robotCode": robot_code,
                "openConversationId": conversation_id,
                "at": {
                    "atUserIds": [
                       staffid 
                    ],
                    "isAtAll": False
                }
            }
        return resp
    
    
    def build_webhook_response(self, reply, data):
        conversation_id = data['conversationId']
        prompt = data['text']['content']
        prompt = prompt.strip()
        img_match_prefix = functions.check_prefix(
            prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
        nick = data['senderNick']
        staffid = data['senderStaffId']
        robotCode = data['robotCode']
        if img_match_prefix and isinstance(reply, list):
            images = ""
            for url in reply:
                images += f"!['IMAGE_CREATE']({url})\n"
            reply = images
            resp = {
                "msgtype": "markdown",
                "markdown": {
                    "title": "IMAGE @" + nick + " ", 
                    "text": images + " \n " + "@" + nick
                },
                "at": {
                    "atUserIds": [
                        staffid
                    ],
                    "isAtAll": False
                }
            }
        else:
            resp = {
                "msgtype": "text",
                "text": {
                    "content": reply
                },
                "at": {
                    "atUserIds": [
                       staffid 
                    ],
                    "isAtAll": False
                }
            }
        return resp
    
    def chat(self, channel, data):
        reply = channel.handle(data)
        type = data['conversationType']
        if type == "1":
            reply_json = self.build_response(reply, data)
            self.notify_dingtalk(data, reply_json)
        else:
            # group的不清楚怎么@，先用webhook调用
            reply_json = self.build_webhook_response(reply, data)
            self.notify_dingtalk_webhook(reply_json)
        

    def notify_dingtalk(self, data, reply_json):
        headers = {
            'content-type': 'application/json', 
            'x-acs-dingtalk-access-token': self.get_token()
        }

        notify_url = self.get_post_url(data)
        try:
            r = requests.post(notify_url, json=reply_json, headers=headers)
            resp = r.json()
            log.info("[DingTalk] response={}".format(str(resp)))
        except Exception as e:
            log.error(e)


class DingTalkChannel(Channel):
    def __init__(self):
        log.info("[DingTalk] started.")

    def startup(self):
        http_app.run(host='0.0.0.0', port=channel_conf(const.DINGTALK).get('port'))

    def handle(self, data):
        reply = "您好，有什么我可以帮助您解答的问题吗？"
        prompt = data['text']['content']
        prompt = prompt.strip()
        if str(prompt) != 0:
            conversation_id = data['conversationId']
            sender_id = data['senderId']
            context = dict()
            img_match_prefix = functions.check_prefix(
                prompt, channel_conf_val(const.DINGTALK, 'image_create_prefix'))
            if img_match_prefix:
                prompt = prompt.split(img_match_prefix, 1)[1].strip()
                context['type'] = 'IMAGE_CREATE'
            id = sender_id
            context['from_user_id'] = str(id)
            reply = super().build_reply_content(prompt, context)
        return reply
         

dd = DingTalkChannel()
handlers = dict()
robots = channel_conf(const.DINGTALK).get('dingtalk_robots')
if robots and len(robots) > 0:
    for robot in robots:
        robot_config = channel_conf(const.DINGTALK).get(robot)
        robot_key = robot_config.get('dingtalk_key')
        group_name = robot_config.get('dingtalk_group')
        handlers[group_name or robot_key] = DingTalkHandler(robot_config)
else:
    handlers['DEFAULT'] = DingTalkHandler(channel_conf(const.DINGTALK))
http_app = Flask(__name__,)


@http_app.route("/", methods=['POST'])
def chat():
    log.info("[DingTalk] chat_headers={}".format(str(request.headers)))
    log.info("[DingTalk] chat={}".format(str(request.data)))
    token = request.headers.get('token')
    data = json.loads(request.data)
    if data:
        content = data['text']['content']
        if not content:
            return
        code = data['robotCode']
        group_name = None
        if 'conversationTitle' in data:
            group_name = data['conversationTitle']
        handler = handlers.get(group_name, handlers.get(code, handlers.get('DEFAULT')))
        if handler.dingtalk_post_token and token != handler.dingtalk_post_token:
            return {'ret': 203}
        handler.chat(dd, data)
        return {'ret': 200}
    
    return {'ret': 201}



```

**Comment by adminlove520** [comment]
单聊现在报错这个：
```
[INFO][2023-05-05 12:45:49][log.py:32] - [DingTalk] chat=b'{"conversationId":"cidw1M9XtXqUwbkQeXnFbDw2m/4PVEPTSsRBgvJjwby6dg=","chatbotCorpId":"dingba6d4de24526572affe93478753d9884","chatbotUserId":"$:LWCP_v1:$e0Rhhrf+yDZksBH2knMNnLwLYZgwKRr6","msgId":"msgAMVBzPulTJGBbGXvR5v4sQ==","senderNick":"\xe5\xa4\xb4\xe7\x9a\xae\xe5\x8f\x91\xe9\xba\xbb","isAdmin":true,"senderStaffId":"2246663532780303","sessionWebhookExpiredTime":1683267349125,"createAt":1683261948877,"senderCorpId":"dingba6d4de24526572affe93478753d9884","conversationType":"1","senderId":"$:LWCP_v1:$JyL/YRce38B73V8MItxj3GBHv+AGfgNM","sessionWebhook":"https://oapi.dingtalk.com/robot/sendBySession?session=f41dd76d7c81d3ab81be3617087ec47c","text":{"content":"\xe4\xbd\xa0\xe6\x98\xaf\xe4\xbb\x80\xe4\xb9\x88"},"robotCode":"dingwjbmfyoxjs27qbwo","msgtype":"text"}'
[INFO][2023-05-05 12:45:49][log.py:32] - [CHATGPT] api_base= proxy=
[INFO][2023-05-05 12:45:49][log.py:32] - [CHATGPT] query=你是什么
[INFO][2023-05-05 12:45:53][log.py:34] - [CHATGPT] reply=我是一个由OpenAI训练的大型语言模型，名为ChatGPT。我旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。
[2023-05-05 12:45:53,573] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/project/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 288, in chat
    handler.chat(dd, data)
  File "/home/project/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 209, in chat
    self.notify_dingtalk(data, reply_json)
  File "/home/project/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 219, in notify_dingtalk
    'x-acs-dingtalk-access-token': self.get_token()
  File "/home/project/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 63, in get_token
    self.get_token_internal()
  File "/home/project/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 53, in get_token_internal
    access_token = data['accessToken']
KeyError: 'accessToken'
59.82.84.86 - - [05/May/2023 12:45:53] "POST / HTTP/1.1" 500 -

```

**Comment by winse** [comment]
你这个是用key和secret获取accesstoken报错。

你的配置贴一下，按理说这三个配置都填了，就是没问题的。可以参考: https://www.zhihu.com/column/c_1635995116149190656

```
          "dingtalk_key": "AppKey",
          "dingtalk_secret": "AppSecret",
          "dingtalk_token": "webhook-access-token",
```

**Comment by xu4wang** [comment]
> 

单聊的时候， dingtalk_token 这个怎么配置？ 谢谢
