### ISSUE TITLE
设置api_base报错

### ISSUE THREAD

**Issue by samkuang1120** [zhayujie/bot-on-anything#278]
我用腾讯云搭建了代理服务器（确认过是可以用的），修改api_base为腾讯云的地址，报错：
[ERROR][2023-04-08 21:38:51][log.py:50] - Invalid URL (POST /chat/completions)
Traceback (most recent call last):
  File "/app/model/openai/chatgpt_model.py", line 50, in reply_text
    response = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /chat/completions)

**Comment by zhayujie** [comment]
看下 openai版本是什么

pip3 show openai

**Comment by samkuang1120** [comment]
/app # pip3 show openai
Name: openai
Version: 0.27.4
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License:
Location: /usr/local/lib/python3.10/site-packages
Requires: requests, aiohttp, tqdm
Required-by:

**Comment by samkuang1120** [comment]
> 看下 openai版本是什么
> 
> pip3 show openai

openai: 0.27.4

**Comment by samkuang1120** [comment]
我是按照以下仓库搭建的腾讯云代理：
https://github.com/Ice-Hazymoon/openai-scf-proxy

**Comment by zhayujie** [comment]
看起来是代理没有生效，无法访问openai

**Comment by samkuang1120** [comment]
> 看起来是代理没有生效，无法访问openai

好的 谢谢.
