### ISSUE TITLE
python3 app.py App startup failed!

### ISSUE THREAD

**Issue by lhyhfut** [zhayujie/bot-on-anything#280]
百度云，CentOS 8.2
[root@wuwang bot-on-anything]# python3 app.py
[ERROR][2023-04-09 16:12:24][log.py:45] - App startup failed!
[ERROR][2023-04-09 16:12:24][log.py:50] - Invalid control character at: line 5 column 71 (char 125)
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    config.load_config()
  File "/root/bot-on-anything/config.py", line 17, in load_config
    config = json.loads(config_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 71 (char 125)

**Comment by UniStart2** [comment]
感觉像config.json文件配置有问题，可能你的json配置文件中有什么不合语法的内容吧，然后python解析json文件时就出现问题了

**Comment by zhayujie** [comment]
看下config.json 的第五行，或者贴一下配置内容看看

**Comment by lhyhfut** [comment]
确实是第5行api_key后面的字符串有问题，我在外面写了一下，复制到服务器中这一行，就没问题了，谢谢！
