### ISSUE TITLE
Bard提示Start up failed on terminal

### ISSUE THREAD

**Issue by Ying3141** [zhayujie/bot-on-anything#290]

**Comment by zhayujie** [comment]
可以发下详细报错吗

**Comment by Ying3141** [comment]
![image](https://user-images.githubusercontent.com/106148175/230892003-60ad1c17-62fa-4f4a-8017-472293d7c060.png)

**Comment by Ying3141** [comment]
![image](https://user-images.githubusercontent.com/106148175/230892825-15b11c6c-666f-4644-b17c-3f1a2b6e94ab.png)
把log.py:47注释掉，报这个错

**Comment by RegimenArsenic** [comment]
可能是配置文件产生了误解，bard的模型type是bard，不是google，配置里对应的对象名称为google而不是bard是因为bard的效果实在是太糟糕了，听说google自己都放弃了这个模型，正在训练新模型，到时候可能会像openai一样有多个不同的模型，所以现在给它预留了多个模型的位置

**Comment by piper-1136** [comment]
然后又出线了这个错误

Please input your question
User:
hello
Bot:
[ERROR][2023-04-10 22:44:04][log.py:47] - [MultiChannel] Start up failed on terminal: No module named 'requests'


配置文件：
model {
type : bard
cookies : xxxxxx
}

**Comment by kettly1260** [comment]
同样不能正常运行


[ERROR][2023-04-13 08:28:20][log.py:47] - [MultiChannel] Start up failed on terminal:
[ERROR][2023-04-13 08:28:20][log.py:45] - App startup failed!
[ERROR][2023-04-13 08:28:20][log.py:50] -
Traceback (most recent call last):
  File "/home/ubuntu/docker/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/home/ubuntu/docker/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/home/ubuntu/docker/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/home/ubuntu/docker/bot-on-anything/channel/terminal/terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "/home/ubuntu/docker/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/ubuntu/docker/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/home/ubuntu/docker/bot-on-anything/model/model_factory.py", line 36, in create_bot
    raise RuntimeError
RuntimeError
