### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by Martin-dq** [zhayujie/bot-on-anything#293]
启动正常，个人订阅号后台发消息回复“该公众号提供的服务出现故障，请稍后再试”，后台报错
我看项目正在更新接入企业微信，sqlite3的参数未设置？
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/python3/lib/python3.9/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/contrib/bottle.py", line 55, in werobot_view
    return robot.get_encrypted_reply(message)
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/robot.py", line 611, in get_encrypted_reply
    reply = self.get_reply(message)
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/robot.py", line 582, in get_reply
    session_storage = self.session_storage
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/utils.py", line 47, in wrapped_func
    setattr(self, prop_name, method(self, *args, **kwargs))
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/robot.py", line 176, in session_storage
    from .session.sqlitestorage import SQLiteStorage
  File "/usr/local/python3/lib/python3.9/site-packages/werobot/session/sqlitestorage.py", line 5, in <module>
    import sqlite3
  File "/usr/local/python3/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/python3/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by Martin-dq** [comment]
"channel": {
    "type": ["terminal"],
    "single_chat_prefix": ["bot", "@bot"],
使用terminal可以正常得到回复，应该是微信订阅号模块的问题
[INFO][2023-04-11 09:54:08][plugin_registry.py:23] - Plugin Selector_v0.1 registered
[INFO][2023-04-11 09:54:08][log.py:32] - [Selector] inited
[WARNING][2023-04-11 09:54:08][log.py:39] - Failed to import plugin createimg
Load config success
[INFO][2023-04-11 09:54:08][log.py:34] - [MultiChannel] Start up chatgpt on terminal

Please input your question
User:
hello
Bot:
Hello! How can I assist you today?

User:
