### ISSUE TITLE
接入bard报错

### ISSUE THREAD

**Issue by bzb1012** [zhayujie/bot-on-anything#303]
![5RD NWW35D17QW1%V V(4L6](https://user-images.githubusercontent.com/118534623/231634218-27a9c468-c726-413f-91b0-b1692ed35ba2.png)

**Comment by RegimenArsenic** [comment]
可能是你的cookie有问题

**Comment by bzb1012** [comment]
> 

![Screenshot_2023-04-14-09-32-55-620_com tencent mm-edit](https://user-images.githubusercontent.com/118534623/231918905-ad224066-2949-472b-b760-5310d7a71f5d.jpg)
请问这个cookie有问题吗？后面的点我去掉还是一样报错

**Comment by bzb1012** [comment]
> 可能是你的cookie有问题

![Screenshot_2023-04-14-09-32-55-620_com tencent mm-edit](https://user-images.githubusercontent.com/118534623/231919360-0bb4c61f-3548-42d6-9022-d7671bdba157.jpg)请问这个cookie有问题吗，后面的点我去掉了也是一样报错。

**Comment by RegimenArsenic** [comment]
你确认一下取的是__Secure-1PSID的cookie吗？google的cookie名字相似的比较多，是不是取错了？

**Comment by bzb1012** [comment]
> 你确认一下取的是__Secure-1PSID的cookie吗？google的cookie名字相似的比较多，是不是取错了？

![image](https://user-images.githubusercontent.com/118534623/232053937-a9b1c73f-6484-4314-a40e-eb0293f46d5d.png)
我取的是这个

**Comment by keshunchen** [comment]
类似的问题，始终提示 Cooke 错误，但浏览器的 Cookie 一直是有效的：

`[WARNING][2023-08-08 11:30:22][log.py:39] - Cookies may be wrong:'NoneType' object has no attribute 'group'
[INFO][2023-08-08 11:30:22][log.py:32] - [Bard] query=你是谁？
[ERROR][2023-08-08 11:30:22][wechat_com_channel.py:76] - 'NoneType' object has no attribute 'ask'
Traceback (most recent call last):
  File "/opt/bot-on-anything/channel/wechat/wechat_com_channel.py", line 72, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/opt/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/opt/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/opt/bot-on-anything/model/google/bard_model.py", line 28, in reply
    answer = bot.ask(query)
AttributeError: 'NoneType' object has no attribute 'ask'`

**Comment by keshunchen** [comment]
参见：https://github.com/zhayujie/bot-on-anything/issues/359
