### ISSUE TITLE
微信登出后，再登入，出现这个错误

### ISSUE THREAD

**Issue by Jeff-Freelancer** [zhayujie/bot-on-anything#310]
Load config success
[WARNING][2023-04-14 00:47:00][log.py:39] - Failed to import plugin createimg
[INFO][2023-04-14 00:47:00][plugin_registry.py:23] - Plugin Selector_v0.1 registered
[INFO][2023-04-14 00:47:00][log.py:32] - [Selector] inited
Load config success
[INFO][2023-04-14 00:47:00][log.py:34] - [MultiChannel] Start up chatgpt on wechat
Please press confirm on your phone.
[ERROR][2023-04-14 00:47:06][log.py:47] - [MultiChannel] Start up failed on wechat: list index out of range
[ERROR][2023-04-14 00:47:06][log.py:45] - App startup failed!
[ERROR][2023-04-14 00:47:06][log.py:50] - list index out of range
Traceback (most recent call last):
  File "app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "app.py", line 23, in start_process
    raise e
  File "app.py", line 20, in start_process
    channel.startup()
  File "/root/bot-on-anything/channel/wechat/wechat_channel.py", line 48, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hot_reload)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 60, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 151, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 196, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

**Comment by zhayujie** [comment]
看下是不是账号被限制了吗

**Comment by Baody12138** [comment]
同，试一下网页版微信能不能登录，不能的话说明账号被限制了。
