### ISSUE TITLE
登陆成功了。应该是收到消息了，但是报错如下。

### ISSUE THREAD

**Issue by 1039752112q** [zhayujie/bot-on-anything#313]
Login successfully as 没有如果
Start auto replying.
[ERROR][2023-04-14 03:28:43][wechat_channel.py:154] - unsupported operand type(s) for |: 'type' and 'NoneType'
Traceback (most recent call last):
  File "/home/ubuntu/bot-on-anything/channel/wechat/wechat_channel.py", line 147, in _do_send
    reply = super().build_reply_content(e_context["context"], e_context["args"])
  File "/home/ubuntu/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/ubuntu/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/home/ubuntu/bot-on-anything/model/model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "/home/ubuntu/bot-on-anything/model/bing/new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "/home/ubuntu/bot-on-anything/model/bing/jailbroken_sydney.py", line 13, in <module>
    class SydneyBot(Chatbot):
  File "/home/ubuntu/bot-on-anything/model/bing/jailbroken_sydney.py", line 17, in SydneyBot
    cookies: dict | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by TNTcraftHIM** [comment]
python版本太低，需要python3.10以上才行

**Comment by defamilo** [comment]
找到newbing的问题了，EdgeGPT 0.1.25.1的Conversation去掉了cookiePath参数，
改下bot-on-anything/model/bing/jailbroken_sydney.py这一行就行（54行源码我注释了换成55行的了）

 52         # 开启新对话
 53         self.chat_hub = SydneyHub(Conversation(
 54             #self.cookiePath, self.cookies, self.proxy))
 55             self.cookies, self.proxy))
 56         self.parent_message_id = message_id if message_id != None else uuid.uuid4()
 57         # 构造历史对话字符串,更新SydneyHubRequest的历史对话
