### ISSUE TITLE
企业微信方式，获取不到Access_token吗这是？

### ISSUE THREAD

**Issue by L12043288** [zhayujie/bot-on-anything#319]
, receiver=LiRenYiXia
[ERROR][2023-04-15 06:27:13][wechat_com_channel.py:61] - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/bot-on-anything/channel/wechat/wechat_com_channel.py", line 59, in _do_send
    self.send(reply_text, reply_user_id)
  File "/opt/bot-on-anything/channel/wechat/wechat_com_channel.py", line 49, in send
    self.client.message.send_text(self.AppId, receiver, msg)
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/client/base.py", line 77, in _request
    kwargs['params']['access_token'] = self.access_token
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/client/base.py", line 238, in access_token
    access_token = self.session.get(self.access_token_key)
  File "/usr/local/python3/lib/python3.10/site-packages/wechatpy/enterprise/client/__init__.py", line 43, in access_token_key
    return '{0}_{1}_access_token'.format(self.corp_id, self.secret[:10])
TypeError: 'NoneType' object is not subscriptable

**Comment by georgeJzzz** [comment]
我也同样的问题 解决了吗  老哥

**Comment by woaiCarlos** [comment]
同问..不知道怎么解决
