### ISSUE TITLE
Start up failed on wechat_com: No module named 'wechatpy'

### ISSUE THREAD

**Issue by reinforceli** [zhayujie/bot-on-anything#330]
[INFO][2023-04-21 16:51:42][log.py:34] - [MultiChannel] Start up chatgpt on wechat_com
[ERROR][2023-04-21 16:51:42][log.py:47] - [MultiChannel] Start up failed on wechat_com: No module named 'wechatpy'
[ERROR][2023-04-21 16:51:42][log.py:45] - App startup failed!
[ERROR][2023-04-21 16:51:42][log.py:50] - No module named 'wechatpy'
Traceback (most recent call last):
  File "app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "app.py", line 23, in start_process
    raise e
  File "app.py", line 19, in start_process
    channel = channel_factory.create_channel(channel_type)
  File "/usr/local/bot-on-anything/channel/channel_factory.py", line 29, in create_channel
    from channel.wechat.wechat_com_channel import WechatEnterpriseChannel
  File "/usr/local/bot-on-anything/channel/wechat/wechat_com_channel.py", line 14, in <module>
    from wechatpy.enterprise.crypto import WeChatCrypto
ModuleNotFoundError: No module named 'wechatpy'

**Comment by vlux** [comment]
pip3 install wehcatpy -U就可以了

**Comment by gongxianhui0** [comment]
> 

请问在哪里使用pip3 install wehcatpy -U
我的回答ERROR: Could not find a version that satisfies the requirement wehcatpy (from versions: none)
ERROR: No matching distribution found for wehcatpy
谢谢
