### ISSUE TITLE
有大佬可以帮忙解决下么

### ISSUE THREAD

**Issue by xbs0325** [zhayujie/bot-on-anything#336]
我是在qq上用bing
最后一步输入这个./go-cqhttp返回的是下面的
D:\Tool\Bot-on-anything-master\bot-on-anything-master\channel\qq>./go-cqhttp
'.' 不是内部或外部命令，也不是可运行的程序

请问怎么解决 就差一步qwq

**Comment by xbs0325** [comment]
解决了 没事了qwq 下错go-cqhttp版本了

**Comment by xbs0325** [comment]
又出现了新的问题
[2023-04-22 16:46:51] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45
[2023-04-22 16:46:51] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证
[2023-04-22 16:46:51] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试

**Comment by yizhitian1145** [comment]
你切换成MacOs登录试一试

**Comment by yizhitian1145** [comment]
如果MACos还不行，就只能换号

**Comment by xbs0325** [comment]
> 

我改成手表登录就好了 但是还是不行 
总是说访问127.0.0.1:8080超时qwq
估计是bot on anything这部分出问题了😭

**Comment by yizhitian1145** [comment]
有报错日志吗

**Comment by xbs0325** [comment]
> 

现在收到信息不提示那个了 但是我这里一个警告device lock is disable http api may fail
一个是心跳功能已关闭 然后收到私聊只显示收到的信息 其他什么都不显示

**Comment by yizhitian1145** [comment]
心跳关闭正常，机器人还能聊天吗

**Comment by xbs0325** [comment]
> 心跳关闭正常，机器人还能聊天吗

我那个机器人聊天的界面好像只有第一次出来了 后面一直没有显示出来

**Comment by xbs0325** [comment]
> 心跳关闭正常，机器人还能聊天吗

阿 机器人界面出来了 那个之前的warning也出来了
上报Event数据到https://127.0.0.1:8080失败:Post"https://127.0.0.1:8080":dial tcp 127.0.0.1:8080 :connectex:No connection could be made because the target machine actively refused it

**Comment by xbs0325** [comment]
> > 心跳关闭正常，机器人还能聊天吗
> 
> 我那个机器人聊天的界面好像只有第一次出来了 后面一直没有显示出来

刚刚channel没设置qq 就显示机器人了 但是我再设qq就没机器人了 然后我发现config.py这个文件里的channal里压根没qq

**Comment by xbs0325** [comment]
Bot:
[ERROR][2023-04-22 22:52:35][log.py:47] - [MultiChannel] Start up failed on terminal: cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\as\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py)
[ERROR][2023-04-22 22:52:35][log.py:45] - App startup failed!
[ERROR][2023-04-22 22:52:35][log.py:50] - cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\as\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py)
Traceback (most recent call last):
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\app.py", line 23, in start_process
    raise e
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\app.py", line 20, in start_process
    channel.startup()
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\channel\terminal\terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\bridge\bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\model\model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\model\bing\new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "D:\Tool\Bot-on-anything-master\bot-on-anything-master\model\bing\jailbroken_sydney.py", line 8, in <module>
    from EdgeGPT import ChatHubRequest, Chatbot, Conversation, ChatHub
ImportError: cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\as\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EdgeGPT.py)
