### ISSUE TITLE
配置为type:bing 服务之后，提示：error: cannot import name 'ChatHubRequest' from 'EdgeGPT'

### ISSUE THREAD

**Issue by iT-Boyer** [zhayujie/bot-on-anything#341]

**Comment by aixinxino** [comment]
我也是这样

**Comment by JimiZhou** [comment]
上周EdgeGPT更新后一直是这个报错

**Comment by Nothingness-Void** [comment]
降级为低版本pip3 install EdgeGPT==0.1.22

**Comment by lsfcode** [comment]
> 降级为低版本pip3 install EdgeGPT==0.1.22



低版本报这个错：

```
[wechat_com_channel.py:61] - unsupported operand type(s) for |: 'type' and 'NoneType'
Traceback (most recent call last):
  File "/home/ubuntu/projects/bot-on-anything/channel/wechat/wechat_com_channel.py", line 57, in _do_send
    reply_text = super().build_reply_content(query, context)
  File "/home/ubuntu/projects/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/home/ubuntu/projects/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/home/ubuntu/projects/bot-on-anything/model/model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "/home/ubuntu/projects/bot-on-anything/model/bing/new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "/home/ubuntu/projects/bot-on-anything/model/bing/jailbroken_sydney.py", line 13, in <module>
    class SydneyBot(Chatbot):
  File "/home/ubuntu/projects/bot-on-anything/model/bing/jailbroken_sydney.py", line 17, in SydneyBot
    cookies: dict | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Nothingness-Void** [comment]
对，我也一样，至今不知道该怎么解，我问bing说｜是Python3.10新增的语法 你可以更换成3.10试试

**Comment by charleschen2006** [comment]
一样一样的。bing模式有谁用起来了嘛？

**Comment by GeekinGH** [comment]
> 一样一样的。bing模式有谁用起来了嘛？

我有用起来，就是速度太慢。

**Comment by Nothingness-Void** [comment]
> > 一样一样的。bing模式有谁用起来了嘛？
> 
> 我有用起来，就是速度太慢。

能看看你的配置和服务器的python版本吗

**Comment by GeekinGH** [comment]
> > > 一样一样的。bing模式有谁用起来了嘛？
> > 
> > 
> > 我有用起来，就是速度太慢。
> 
> 能看看你的配置和服务器的python版本吗
Python 3.10.6
配置应该和你没有区别

**Comment by lsfcode** [comment]
> > > 一样一样的。bing模式有谁用起来了嘛？
> > 
> > 
> > 我有用起来，就是速度太慢。
> 
> 能看看你的配置和服务器的python版本吗

换成3.10确实可用了，不过bing配置里的越狱要关掉，不然会报另外一个错。另外，bing的回复非常慢，我又换回chatgpt了，毕竟我也不太需要时效性很强的内容

**Comment by abwuge** [comment]
我修复了这个bug，不过速度慢无解。这是Bing的正常速度，只不过一些方案是bing回复了多少就显示多少内容，这个是bing完全回复后再显示内容。
