### ISSUE TITLE
企业问些设置的时候提示openapi回调地址不正确

### ISSUE THREAD

**Issue by zhangzzgz** [zhayujie/bot-on-anything#346]
终端提示：
[2023-04-26 11:12:50,650] ERROR in app: Exception on /wechat [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bot-on-anything-1.1.0/channel/wechat/wechat_com_channel.py", line 27, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/home/bot-on-anything-1.1.0/channel/wechat/wechat_com_channel.py", line 72, in handle
    echostr = self.crypto.check_signature(signature, timestamp, nonce, echostr)
  File "/usr/local/lib/python3.8/dist-packages/wechatpy/enterprise/crypto.py", line 23, in check_signature
    return self._check_signature(
  File "/usr/local/lib/python3.8/dist-packages/wechatpy/crypto/__init__.py", line 60, in _check_signature
    pc = crypto_class(self.key)
  File "/usr/local/lib/python3.8/dist-packages/wechatpy/crypto/base.py", line 21, in __init__
    self.cipher = WeChatCipher(key)
  File "/usr/local/lib/python3.8/dist-packages/wechatpy/crypto/cryptography.py", line 25, in __init__
    Cipher(
TypeError: __init__() missing 1 required positional argument: 'backend'
106.55.201.217 - - [26/Apr/2023 11:12:50] "GET /wechat?msg_signa. TA%3D%3D HTTP/1.1" 500 -

**Comment by ck7968** [comment]
#306 
看下这个。

**Comment by zhangzzgz** [comment]
> 

能用了，谢谢
