### ISSUE TITLE
必应交互出错：TypeError: string indices must be integers

### ISSUE THREAD

**Issue by CatcherX** [zhayujie/bot-on-anything#379]
> py .\app.py
Load config success
[WARNING][2023-05-14 13:19:16][log.py:39] - Failed to import plugin createimg
[INFO][2023-05-14 13:19:16][plugin_registry.py:23] - Plugin Selector_v0.1 registered
[INFO][2023-05-14 13:19:16][log.py:32] - [Selector] inited
Load config success
[INFO][2023-05-14 13:19:16][log.py:34] - [MultiChannel] Start up bing on terminal

Please input your question
User:
你好
1
Bot:
[ERROR][2023-05-14 13:20:05][log.py:47] - [MultiChannel] Start up failed on terminal: string indices must be integers
[ERROR][2023-05-14 13:20:05][log.py:45] - App startup failed!
[ERROR][2023-05-14 13:20:05][log.py:50] - string indices must be integers
Traceback (most recent call last):
  File "G:\py\chatgpt\bot-on-anything\app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "G:\py\chatgpt\bot-on-anything\app.py", line 23, in start_process
    raise e
  File "G:\py\chatgpt\bot-on-anything\app.py", line 20, in start_process
    channel.startup()
  File "G:\py\chatgpt\bot-on-anything\channel\terminal\terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "G:\py\chatgpt\bot-on-anything\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "G:\py\chatgpt\bot-on-anything\bridge\bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "G:\py\chatgpt\bot-on-anything\model\bing\new_bing_model.py", line 95, in reply
    answer = asyncio.run(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "G:\py\chatgpt\bot-on-anything\model\bing\jailbroken_sydney.py", line 110, in ask
    self.update_reply_cache(response["item"]["messages"][-1])
TypeError: string indices must be integers

**Comment by CatcherX** [comment]
降低NewBing的版本后正常

**Comment by hechong1215** [comment]
> 降低NewBing的版本后正常

请问要降到多少？
