### ISSUE TITLE
Internal Server Error  The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by nmww** [zhayujie/bot-on-anything#382]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

`bot-on-anything-master/channel/http/auth.py", line 53, in decode_auth_token
    payload = jwt.decode(auth_token, channel_conf(const.HTTP).get(
AttributeError: module 'jwt' has no attribute 'decode'

During handling of the above exception, another exception occurred:`

`bot-on-anything-master/channel/http/auth.py", line 93, in identify
    payload = Auth.decode_auth_token(authorization)
  File "/www/wwwroot/gpt.jingchengbang.com/bot-on-anything-master/channel/http/auth.py", line 59, in decode_auth_token
    except jwt.ExpiredSignatureError:
AttributeError: module 'jwt' has no attribute 'ExpiredSignatureError'

During handling of the above exception, another exception occurred:`

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/62239e6c0f995ae1fdc00d18b7905eac_venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/62239e6c0f995ae1fdc00d18b7905eac_venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/62239e6c0f995ae1fdc00d18b7905eac_venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/62239e6c0f995ae1fdc00d18b7905eac_venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/channel/http/http_channel.py", line 89, in index
    if (auth.identify(request) == False):
  File "/www/wwwroot/gpt.A.com/bot-on-anything-master/channel/http/auth.py", line 104, in identify
    except jwt.ExpiredSignatureError:
AttributeError: module 'jwt' has no attribute 'ExpiredSignatureError'
115.171.20.255 - - [16/May/2023 03:52:08] "[35m[1mGET / HTTP/1.1[0m" 500 -`

**Comment by cocsea** [comment]
一模一样，怎么解决啊

**Comment by superpig33** [comment]
引用的库冲突了，检查一下本地是不是有一个jwt、PyJWT，实际使用的是PyJWT
