### ISSUE TITLE
接入bing时报错

### ISSUE THREAD

**Issue by Angasky** [zhayujie/bot-on-anything#389]
[INFO][2023-05-23 23:17:52][log.py:34] - [MultiChannel] Start up bing on terminal

Please input your question
User:
123
Bot:
[ERROR][2023-05-23 23:17:56][log.py:47] - [MultiChannel] Start up failed on terminal: cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\angasky\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py)
[ERROR][2023-05-23 23:17:56][log.py:45] - App startup failed!
[ERROR][2023-05-23 23:17:56][log.py:50] - cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\angasky\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py)
Traceback (most recent call last):
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\app.py", line 23, in start_process
    raise e
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\app.py", line 20, in start_process
    channel.startup()
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\channel\terminal\terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\channel\channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\bridge\bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\model\model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\model\bing\new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "C:\Users\angasky\Desktop\webot\bot-on-anything-master\model\bing\jailbroken_sydney.py", line 8, in <module>
    from EdgeGPT import ChatHubRequest, Chatbot, Conversation, ChatHub
ImportError: cannot import name 'ChatHubRequest' from 'EdgeGPT' (C:\Users\angasky\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py)

**Comment by Peteroyu** [comment]
导包问题，版本不兼容
