### ISSUE TITLE
App startup failed!

### ISSUE THREAD

**Issue by xhmooc** [zhayujie/bot-on-anything#405]
启动后出现
[ERROR][2023-06-01 10:41:41][log.py:45] - App startup failed!
[ERROR][2023-06-01 10:41:41][log.py:50] - cannot import name 'ChatHubRequest' from 'EdgeGPT' (/usr/local/Python3.9.1/lib/python3.9/site-packages/EdgeGPT.py)
Traceback (most recent call last):
  File "/root/bot-on-anything-1.1.0/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/root/bot-on-anything-1.1.0/app.py", line 23, in start_process
    raise e
  File "/root/bot-on-anything-1.1.0/app.py", line 20, in start_process
    channel.startup()
  File "/root/bot-on-anything-1.1.0/channel/terminal/terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "/root/bot-on-anything-1.1.0/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/bot-on-anything-1.1.0/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/root/bot-on-anything-1.1.0/model/model_factory.py", line 29, in create_bot
    from model.bing.new_bing_model import BingModel
  File "/root/bot-on-anything-1.1.0/model/bing/new_bing_model.py", line 9, in <module>
    from model.bing.jailbroken_sydney import SydneyBot
  File "/root/bot-on-anything-1.1.0/model/bing/jailbroken_sydney.py", line 8, in <module>
    from EdgeGPT import ChatHubRequest, Chatbot, Conversation, ChatHub
ImportError: cannot import name 'ChatHubRequest' from 'EdgeGPT' (/usr/local/Python3.9.1/lib/python3.9/site-packages/EdgeGPT.py)

**Comment by Kiteflyingee** [comment]
同样的
