### ISSUE TITLE
newbing在replit中接入微信扫码后出现以下情况

### ISSUE THREAD

**Issue by youyi0218** [zhayujie/bot-on-anything#408]
所有库都安装完毕，运行可以正常出现二维码，也可以正常扫码。扫码后就出现以下报错
ERROR][2023-06-03 05:04:45][log.py:47] - [MultiChannel] Start up failed on wechat: mismatched tag: line 64, column 4
[ERROR][2023-06-03 05:04:45][log.py:45] - App startup failed!
[ERROR][2023-06-03 05:04:45][log.py:50] - mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "/home/runner/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/home/runner/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/home/runner/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/home/runner/bot-on-anything/channel/wechat/wechat_channel.py", line 48, in startup
    itchat.auto_login(enableCmdQR=2, hotReload=hot_reload)
  File "/home/runner/bot-on-anything/venv/lib/python3.10/site-packages/itchat/components/register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/runner/bot-on-anything/venv/lib/python3.10/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/home/runner/bot-on-anything/venv/lib/python3.10/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/home/runner/bot-on-anything/venv/lib/python3.10/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

**Comment by mari1995** [comment]
我也出现了
