### ISSUE TITLE
请求一下这个报错是为什么啊

### ISSUE THREAD

**Issue by Peteroyu** [zhayujie/bot-on-anything#420]
[ERROR][2023-06-21 16:25:06][log.py:50] - 'Conversation' object has no attribute 'struct'
Traceback (most recent call last):
  File "/opt/software/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/opt/software/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/opt/software/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/opt/software/bot-on-anything/channel/terminal/terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/software/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/software/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/software/bot-on-anything/model/bing/new_bing_model.py", line 95, in reply
    answer = asyncio.run(task)
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 105, in ask
    async for final, response in self.ask_stream(
  File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 54, in ask_stream
    self.chat_hub = SydneyHub(Conversation(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 142, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Conversation' object has no attribute 'struct'

**Comment by RealMarco** [comment]
我遇到了同样的错误。 你解决了吗？

**Comment by RealMarco** [comment]
> [ERROR][2023-06-21 16:25:06][log.py:50] - 'Conversation' object has no attribute 'struct' Traceback (most recent call last): File "/opt/software/bot-on-anything/app.py", line 42, in main start_process(channel_type[0], args.config) File "/opt/software/bot-on-anything/app.py", line 23, in start_process raise e File "/opt/software/bot-on-anything/app.py", line 20, in start_process channel.startup() File "/opt/software/bot-on-anything/channel/terminal/terminal_channel.py", line 21, in startup for res in super().build_reply_content(prompt, context): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/software/bot-on-anything/channel/channel.py", line 31, in build_reply_content return Bridge().fetch_reply_content(query, context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/software/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content return model_factory.create_bot(type).reply(query, context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/software/bot-on-anything/model/bing/new_bing_model.py", line 95, in reply answer = asyncio.run(task) ^^^^^^^^^^^^^^^^^ File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/python3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 105, in ask async for final, response in self.ask_stream( File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 54, in ask_stream self.chat_hub = SydneyHub(Conversation( ^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/software/bot-on-anything/model/bing/jailbroken_sydney.py", line 142, in **init** conversation_signature=conversation.struct["conversationSignature"], ^^^^^^^^^^^^^^^^^^^ AttributeError: 'Conversation' object has no attribute 'struct'

我遇到了同样的错误。 你解决了吗？

**Comment by Peteroyu** [comment]
没有
