### ISSUE TITLE
KeyError: 'senderStaffId'

### ISSUE THREAD

**Issue by xu4wang** [zhayujie/bot-on-anything#439]
大家有碰到吗？

```
[INFO][2023-07-23 23:36:01][log.py:32] - [CHATGPT] api_base= proxy=
[INFO][2023-07-23 23:36:01][log.py:32] - [CHATGPT] query=hello
[INFO][2023-07-23 23:36:02][log.py:34] - [CHATGPT] reply=Hello! How can I assist you today?
[2023-07-23 23:36:02,782] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/user01/myenv38/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user01/myenv38/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user01/myenv38/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user01/myenv38/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user01/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 288, in chat
    handler.chat(dd, data)
  File "/home/user01/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 212, in chat
    reply_json = self.build_webhook_response(reply, data)
  File "/home/user01/bot-on-anything/channel/dingtalk/dingtalk_channel.py", line 169, in build_webhook_response
    staffid = data['senderStaffId']
KeyError: 'senderStaffId'
59.82.84.8 - - [23/Jul/2023 23:36:02] "POST / HTTP/1.1" 500 -
```

**Comment by YuJunping** [comment]
我也遇到了，怎么解决呀

**Comment by xu4wang** [comment]
> 我也遇到了，怎么解决呀

好像在正式环境没问题。

**Comment by YuJunping** [comment]
> > 我也遇到了，怎么解决呀
> 
> 好像在正式环境没问题。
正式环境指的什么
