### ISSUE TITLE
bard使用 聊天就报错闪退

### ISSUE THREAD

**Issue by mianlaodie** [zhayujie/bot-on-anything#444]
Please input your question
User:
mnmn
Bot:
[WARNING][2023-08-25 03:09:31][log.py:39] - Cookies may be wrong:'NoneType' object has no attribute 'group'
[ERROR][2023-08-25 03:09:31][log.py:47] - [MultiChannel] Start up failed on terminal: 'NoneType' object has no attribute 'ask'
[ERROR][2023-08-25 03:09:31][log.py:45] - App startup failed!
[ERROR][2023-08-25 03:09:31][log.py:50] - 'NoneType' object has no attribute 'ask'
Traceback (most recent call last):
  File "/root/bot-on-anything/app.py", line 42, in main
    start_process(channel_type[0], args.config)
  File "/root/bot-on-anything/app.py", line 23, in start_process
    raise e
  File "/root/bot-on-anything/app.py", line 20, in start_process
    channel.startup()
  File "/root/bot-on-anything/channel/terminal/terminal_channel.py", line 21, in startup
    for res in super().build_reply_content(prompt, context):
  File "/root/bot-on-anything/channel/channel.py", line 31, in build_reply_content
    return Bridge().fetch_reply_content(query, context)
  File "/root/bot-on-anything/bridge/bridge.py", line 18, in fetch_reply_content
    return model_factory.create_bot(type).reply(query, context)
  File "/root/bot-on-anything/model/google/bard_model.py", line 28, in reply
    answer = bot.ask(query)
AttributeError: 'NoneType' object has no attribute 'ask'

**Comment by mianlaodie** [comment]
cookies确定是正确的

**Comment by 1352608667** [comment]
WARNING][2023-08-31 16:05:01][log.py:39] - HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))有出现这个东西吗
