### ISSUE TITLE
tg使用失败，错误信息如图，请问如何处理？

### ISSUE THREAD

**Issue by wudaweixxx** [zhayujie/bot-on-anything#67]
config.json如图：
![image](https://user-images.githubusercontent.com/67285482/222913320-16465d17-8ec9-4d9d-a29f-e434c36fa9a4.png)

docker容器中运行app.py后，在tg中机器人对话框发送消息，错误信息如图：
![image](https://user-images.githubusercontent.com/67285482/222913528-7e12cafe-f42e-4461-9c26-3956898cd703.png)

请问如何处理？谢谢！

**Comment by Lancenas** [comment]
** telegram bot同上一样的错误提示？**
root@website:/home/bot-on-anything# python3 app.py
[INFO][2023-03-04 10:23:13][log.py:34] - [INIT] Start up: chatgpt on telegram
[INFO][2023-03-04 10:23:13][telegram_channel.py:27] - 开始启动[telegram]机器人
2023-03-04 10:23:29,302 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'NoneType' object is not iterable"
2023-03-04 10:23:29,302 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.9/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.9/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.9/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.9/dist-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.9/dist-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/home/bot-on-anything/channel/telegram/telegram_channel.py", line 20, in send_welcome
    TelegramChannel().handle(msg)
  File "/home/bot-on-anything/channel/telegram/telegram_channel.py", line 32, in handle
    img_match_prefix = self.check_prefix(msg, channel_conf_val(const.TELEGRAM, 'image_create_prefix'))
  File "/home/bot-on-anything/channel/telegram/telegram_channel.py", line 71, in check_prefix
    for prefix in prefix_list:
TypeError: 'NoneType' object is not iterable
"

**Comment by zhayujie** [comment]
是每个问题都会有这个报错吗？

**Comment by Lancenas** [comment]
> 是每个问题都会有这个报错吗？

每个 telegram bot 提问都报错。

**Comment by wudaweixxx** [comment]
问题已经解决。 配置文件中的对话前缀定义不能删除 要保留....

**Comment by zhayujie** [comment]
> 问题已经解决。 配置文件中的对话前缀定义不能删除 要保留....

哦哦 那几个配置是共享的
