### ISSUE TITLE
你们都是怎么解决微信无法登录的问题的，似乎和网页版微信有关

### ISSUE THREAD

**Issue by curiosity2** [zhayujie/bot-on-anything#88]
[ERROR][2023-03-06 10:55:45][log.py:45] - App startup failed!
[ERROR][2023-03-06 10:55:45][log.py:50] - 'wxsid'
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    channel.startup()
  File "/mnt/d/Projects/bot-on-anything/channel/wechat/wechat_channel.py", line 38, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.8/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.8/site-packages/itchat/components/login.py", line 55, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/site-packages/itchat/components/login.py", line 142, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/site-packages/itchat/components/login.py", line 184, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by zhayujie** [comment]
一般原因为使用了itchat且无法登录网页版微信，解决方法是先卸载itchat，然后安装itchat-uos 1.5.0.dev0版本。

**Comment by curiosity2** [comment]
> 一般原因为使用了itchat且无法登录网页版微信，解决方法是先卸载itchat，然后安装itchat-uos 1.5.0.dev0版本。

结合这条可以正常登陆了，https://github.com/why2lyj/ItChat-UOS/pull/14#issue-1327505309
